/* spu_workloads.c -- GENERATED by tools/build_spu_workloads.py.
 * Registers the 1 lifted SPU images of "tornado" with the workload
 * dispatch registry (by FNV-1a-64 image fingerprint) and populates each image's
 * indirect-branch table under a distinct image id. cellSpurs AddWorkload/
 * CreateTask/RunJobChain call spu_workload_dispatch(), which fingerprints the
 * guest image, finds the lifted entry here, and runs it on a fresh local store.
 * Build note: add <repo>/runtime/spu to this target's include dirs (the lifted
 * sources use bare #include "spu_context.h" etc.). */
#include "spu_workload.h"

extern void spu_begin_image(int image_id);

/* per-image extern decls (prefixed entry fn + recomp_register) */
extern void spu_0000_at_00518880_spu_func_00000108(spu_context*);
extern void spu_0000_at_00518880_spu_recomp_register(void);

void tornado_spu_register_all(void)
{
    spu_begin_image(1); spu_0000_at_00518880_spu_recomp_register();
    spu_workload_register_img(0x2291549BC58CD5B7ULL, spu_0000_at_00518880_spu_func_00000108, 1, "spu_0000_at_00518880");
    spu_workload_register_img(0x5C94B09593BC2B2AULL, spu_0000_at_00518880_spu_func_00000108, 1, "spu_0000_at_00518880.text");
    spu_begin_image(0);
}

/* Auto-register at startup (before the game adds any SPURS workload/task). */
__attribute__((constructor)) static void tornado_spu_register_all_ctor(void)
{
    tornado_spu_register_all();
}
