/* GENERATED by tools/relift.sh: the lifted SPURS job binaries. */
#include "spu_workload.h"
extern void spu_begin_image(int image_id);
extern void job_180A7D9692D05324_spu_func_00000000(spu_context*); extern void job_180A7D9692D05324_spu_recomp_register(void);
extern void job_1B1373BE58F47252_spu_func_00000000(spu_context*); extern void job_1B1373BE58F47252_spu_recomp_register(void);
extern void job_245B9FBE9293D219_spu_func_00000000(spu_context*); extern void job_245B9FBE9293D219_spu_recomp_register(void);
extern void job_B9B94FC2A8C5C2EF_spu_func_00000000(spu_context*); extern void job_B9B94FC2A8C5C2EF_spu_recomp_register(void);
extern void job_DBDFACBCFF74DEE5_spu_func_00000000(spu_context*); extern void job_DBDFACBCFF74DEE5_spu_recomp_register(void);
extern void job_E13F736227DA5AAE_spu_func_00000000(spu_context*); extern void job_E13F736227DA5AAE_spu_recomp_register(void);
__attribute__((constructor)) static void tornado_spu_jobs_register(void)
{
    spu_begin_image(2); job_180A7D9692D05324_spu_recomp_register();
    spu_workload_register_img(0x180A7D9692D05324ULL, job_180A7D9692D05324_spu_func_00000000, 2, "job_180A7D9692D05324");
    spu_begin_image(3); job_1B1373BE58F47252_spu_recomp_register();
    spu_workload_register_img(0x1B1373BE58F47252ULL, job_1B1373BE58F47252_spu_func_00000000, 3, "job_1B1373BE58F47252");
    spu_begin_image(4); job_245B9FBE9293D219_spu_recomp_register();
    spu_workload_register_img(0x245B9FBE9293D219ULL, job_245B9FBE9293D219_spu_func_00000000, 4, "job_245B9FBE9293D219");
    spu_begin_image(5); job_B9B94FC2A8C5C2EF_spu_recomp_register();
    spu_workload_register_img(0xB9B94FC2A8C5C2EFULL, job_B9B94FC2A8C5C2EF_spu_func_00000000, 5, "job_B9B94FC2A8C5C2EF");
    spu_begin_image(6); job_DBDFACBCFF74DEE5_spu_recomp_register();
    spu_workload_register_img(0xDBDFACBCFF74DEE5ULL, job_DBDFACBCFF74DEE5_spu_func_00000000, 6, "job_DBDFACBCFF74DEE5");
    spu_begin_image(7); job_E13F736227DA5AAE_spu_recomp_register();
    spu_workload_register_img(0xE13F736227DA5AAEULL, job_E13F736227DA5AAE_spu_func_00000000, 7, "job_E13F736227DA5AAE");
    spu_begin_image(0);
}
