#!/bin/sh
# Regenerate everything git-ignored: imports.json, the lifted PPU tree, the HLE
# NID table and the lifted SPU images. Run from the repo root.
set -e
PS3RECOMP="${PS3RECOMP:-/g/recomp/ps3}"

# The executable sections are .init, .text (0x10230..0x4F8700), .fini and the
# .lib.stub import trampolines (0x4F8724..0x4F9404, 103 stubs). --code-end sits
# just past the stubs so --hle-stubs has something to rewrite, and no further:
# everything above is .rodata in the same R-X segment.
CODE_END=0x4F9404

python "$PS3RECOMP/tools/gen_imports.py" game/EBOOT.elf -o imports.json
python "$PS3RECOMP/tools/find_functions.py" game/EBOOT.elf --output analysis/functions.json

rm -rf src/recomp src/gen && mkdir -p src/recomp src/gen
python "$PS3RECOMP/tools/ppu_lifter.py" game/EBOOT.elf \
    --functions analysis/functions.json \
    --hle-stubs imports.json \
    --code-end "$CODE_END" \
    -o src/recomp

python "$PS3RECOMP/tools/gen_hle_nids.py" --all --out src/gen/ppu_hle_nids.cpp

# ---- SPU: the one embedded image ---------------------------------------------
python "$PS3RECOMP/tools/extract_spu_images.py" game/EBOOT.elf --out analysis/spu
rm -rf src/spu_gen && mkdir -p src/spu_gen
python "$PS3RECOMP/tools/build_spu_workloads.py" \
    --images analysis/spu --lifted src/spu_gen \
    --out src/spu_gen/spu_workloads.c \
    --register-fn tornado_spu_register_all --constructor --title tornado

# ---- SPURS job binaries (Wwise's audio jobs) --------------------------------
# Raw code+data blobs the title hands to its job chain, loaded at LS 0 -- not
# ELFs, so the extractor cannot see them. Capture from a run that reaches the
# menu and past the first save (that is when the third one first runs):
#
#   SPU_DUMP_MISS=spu_miss PAD_SCRIPT="18:0x0008,50:0x4000,70:0x4000" \
#       ./build/tornado vfs/PS3_GAME/USRDIR/EBOOT.elf
#
# Unlifted, each MISSes, completes empty, and Wwise waits forever for audio it
# never gets -- the main thread wedges right after the New Game save.
OUT=src/spu_gen/spu_jobs.c
IMG=2
{
  echo "/* GENERATED by tools/relift.sh: the lifted SPURS job binaries. */"
  echo "#include \"spu_workload.h\""
  echo "extern void spu_begin_image(int image_id);"
} > "$OUT.tmp"
REG=""
for J in spu_miss/spujob_*.bin; do
    [ -f "$J" ] || continue
    FP=$(basename "$J" .bin | cut -d_ -f2)
    P="job_${FP}_"
    python "$PS3RECOMP/tools/find_spu_functions.py" "$J" --raw --base 0 \
        --out "spu_miss/job_${FP}_funcs.json"
    rm -rf "src/spu_gen/job_$FP" && mkdir -p "src/spu_gen/job_$FP"
    python "$PS3RECOMP/tools/spu_lifter.py" "$J" --base 0 \
        --functions "spu_miss/job_${FP}_funcs.json" \
        --symbol-prefix "$P" -o "src/spu_gen/job_$FP"
    echo "extern void ${P}spu_func_00000000(spu_context*); extern void ${P}spu_recomp_register(void);" >> "$OUT.tmp"
    REG="$REG    spu_begin_image($IMG); ${P}spu_recomp_register();
    spu_workload_register_img(0x${FP}ULL, ${P}spu_func_00000000, $IMG, \"job_$FP\");
"
    IMG=$((IMG + 1))
done
{
  echo "__attribute__((constructor)) static void tornado_spu_jobs_register(void)"
  echo "{"
  printf "%s" "$REG"
  echo "    spu_begin_image(0);"
  echo "}"
} >> "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
